// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hightqual_it_backend.Tools;

#nullable disable

namespace hightqual_it_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220516123313_ajoutCommentary")]
    partial class ajoutCommentary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("hightqual_it_backend.Models.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CpuId")
                        .HasColumnType("int");

                    b.Property<int?>("CriticalStockId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MouseId")
                        .HasColumnType("int");

                    b.Property<int>("NbVente")
                        .HasColumnType("int");

                    b.Property<int?>("OsId")
                        .HasColumnType("int");

                    b.Property<int?>("PowerSupplyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<int?>("ScreenId")
                        .HasColumnType("int");

                    b.Property<int?>("SoundId")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CpuId");

                    b.HasIndex("CriticalStockId");

                    b.HasIndex("MouseId");

                    b.HasIndex("OsId");

                    b.HasIndex("PowerSupplyId");

                    b.HasIndex("ScreenId");

                    b.HasIndex("SoundId");

                    b.HasIndex("StockId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("SampleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("SampleId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Commentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("Date_post")
                        .HasColumnType("longtext");

                    b.Property<string>("Product_name")
                        .HasColumnType("longtext");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Commentaries");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Commentary")
                        .HasColumnType("longtext");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Device.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Mouses");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Device.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .HasColumnType("longtext");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ProductRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Reference")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.CriticalStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("CriticalStocks");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderRef")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductRef")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Cpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CpuMemoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int>("NbCore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CpuMemoryId");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.GraphicProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ComputerId");

                    b.HasIndex("MemoryId");

                    b.ToTable("GraphicProducts");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.HardDisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<double>("Capacity")
                        .HasColumnType("double");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ComputerId");

                    b.ToTable("HardDisks");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Memory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Capacity")
                        .HasColumnType("longtext");

                    b.Property<int?>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ComputerId");

                    b.ToTable("Memories");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Os", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Oss");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Power")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PowerSupplies");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Sound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .HasColumnType("longtext");

                    b.Property<string>("Power")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Computer", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("hightqual_it_backend.Models.Logistic.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("hightqual_it_backend.Models.Motherboard.Cpu", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId");

                    b.HasOne("hightqual_it_backend.Models.Logistic.CriticalStock", "CriticalStock")
                        .WithMany()
                        .HasForeignKey("CriticalStockId");

                    b.HasOne("hightqual_it_backend.Models.Device.Mouse", "Mouse")
                        .WithMany()
                        .HasForeignKey("MouseId");

                    b.HasOne("hightqual_it_backend.Models.Motherboard.Os", "Os")
                        .WithMany()
                        .HasForeignKey("OsId");

                    b.HasOne("hightqual_it_backend.Models.Motherboard.PowerSupply", "PowerSupply")
                        .WithMany()
                        .HasForeignKey("PowerSupplyId");

                    b.HasOne("hightqual_it_backend.Models.Device.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId");

                    b.HasOne("hightqual_it_backend.Models.Motherboard.Sound", "Sound")
                        .WithMany()
                        .HasForeignKey("SoundId");

                    b.HasOne("hightqual_it_backend.Models.Logistic.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Cpu");

                    b.Navigation("CriticalStock");

                    b.Navigation("Mouse");

                    b.Navigation("Os");

                    b.Navigation("PowerSupply");

                    b.Navigation("Screen");

                    b.Navigation("Sound");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Color", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("Colors")
                        .HasForeignKey("ComputerId");

                    b.HasOne("hightqual_it_backend.Models.Detail.Image", "Sample")
                        .WithMany()
                        .HasForeignKey("SampleId");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Commentary", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("Commentaries")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Image", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("Images")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Detail.Rank", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("Ranks")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Device.Mouse", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Device.Screen", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Cart", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.OrderDetail", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Logistic.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("hightqual_it_backend.Models.Computer", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Tag", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("Tags")
                        .HasForeignKey("ComputerId");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Connector", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Computer", "Computer")
                        .WithMany("Connectors")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Cpu", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("hightqual_it_backend.Models.Motherboard.Memory", "CpuMemory")
                        .WithMany()
                        .HasForeignKey("CpuMemoryId");

                    b.Navigation("Brand");

                    b.Navigation("CpuMemory");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.GraphicProduct", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("GraphProds")
                        .HasForeignKey("ComputerId");

                    b.HasOne("hightqual_it_backend.Models.Motherboard.Memory", "Memory")
                        .WithMany()
                        .HasForeignKey("MemoryId");

                    b.Navigation("Brand");

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.HardDisk", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("hightqual_it_backend.Models.Computer", "Computer")
                        .WithMany("HardDisks")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Brand");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Memory", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("hightqual_it_backend.Models.Computer", null)
                        .WithMany("Memories")
                        .HasForeignKey("ComputerId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.PowerSupply", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("hightqual_it_backend.Models.Logistic.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Motherboard.Sound", b =>
                {
                    b.HasOne("hightqual_it_backend.Models.Detail.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Computer", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Commentaries");

                    b.Navigation("Connectors");

                    b.Navigation("GraphProds");

                    b.Navigation("HardDisks");

                    b.Navigation("Images");

                    b.Navigation("Memories");

                    b.Navigation("Ranks");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("hightqual_it_backend.Models.Logistic.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
