version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: qual_it
  MYSQL_USER: user
  MYSQL_PASSWORD: password

services:
  mysql_qual_it:
    container_name: mysql_qual_it
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - dbQualIt:/var/lib/mysql
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - 9906:3306
    networks:
        - qual_it_network
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: qual_it_host
  adminer:
      image: adminer:latest
      container_name: adminer
      restart: unless-stopped
      ports:
        - 8000:8080
      networks:
        - qual_it_network
      depends_on:
        - mysql_qual_it
      environment:
        ADMINER_DEFAULT_SERVER: mysql_qual_it
volumes:
  dbQualIt:

networks: 
  qual_it_network: {}
